import "./globals.css";
import { Sora } from "@next/font/google";
import { Bungee } from "@next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
<<<<<<< HEAD
import Background from "@/components/Background";
=======
>>>>>>> 9b46047 (set up initial layout)
import { ThemeProvider } from "@/components/ThemeProvider";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

const bungee = Bungee({
  subsets: ["latin"],
  variable: "--font-bungee",
  weight: ["400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        classNameX={`page bg-site bg-cover bg-no-repeat ${sora.variable} font-bungee relative`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
<<<<<<< HEAD
          <Background />
=======
>>>>>>> 9b46047 (set up initial layout)
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
